### PR TITLE
New Invariant Model

### PR DESCRIPTION
**Pull request by Frostweeds**
- Add assume function in library
- Replace pre-condition with assumes in contract method
- Place HavocInjection  before InvariantInjection
- Add implicit constructor
- Add static reference and two new global invariants : one for the cast on the statis refs and one for the call to their invariant.
- Improve havoc injection
- Inject invariant only in public method
- Add examples for public/private + update old examples to new model

### CODE REVIEW

**Comment by jad-hamza** [comment]
In that example:

```scala
import stainless.smartcontracts._
import stainless.annotation._

trait RequireAssume extends Contract {
  var x: BigInt

  @solidityView
  @solidityPublic
  def foo() = {
  }

  def invariant() = {
    x >= 0
  }

  def constructor() = {
    x = 0
  }
}
```

`require` and `assume` are inserted, why not just `assume`?

```scala
[ Debug  ] Symbols after ContractMethodLifting
[ Debug  ] 
[ Debug  ] -------------Functions-------------
[ Debug  ] @solidityView
[ Debug  ] @solidityPublic
[ Debug  ] def foo(env: Environment, msg: Msg, callee: Address): Unit = {
[ Debug  ]   require(env.contractAt(callee).isInstanceOf[RequireAssume])
[ Debug  ]   assume(invariant(env, callee) && (refCastInvariant(env) && invariant(env, addressOfRequireAssume)))
[ Debug  ]   ()
[ Debug  ] } ensuring {
[ Debug  ]   (res: Unit) => (invariant(env, callee) && (refCastInvariant(env) && invariant(env, addressOfRequireAssume))) && true
[ Debug  ] }
```

**Comment by Frostweeds** [comment]
It is an oversight. Initially, I introduce the `require` because it was easier to debug. Stainless would report a failing VC if I was forwarding the wrong `callee`. I'll fix that soon.

**Comment by jad-hamza** [comment]
The examples `FieldMutated` and `Reentrancy` from `failVerification` are going through on this branch

**Comment by jad-hamza** [comment]
Merged, thanks!

**Pull request merged**
